### ISSUE TITLE
All you get back from subscribeToMore is actually the unsubscribe handle

### ISSUE THREAD

**Issue by alexicum** [bmsantos/graphql_subscriptions_issue#8]
Example not working with latest react-apollo, here is reason:
https://github.com/apollographql/apollo-client/issues/1145

Should be:
`  this.unsubscribe = nextProps.data.subscribeToMore({`
and:
```
  // if the feed has changed, we need to unsubscribe before resubscribing
  this.unsubscribe();
```
same in componentWillUnmount()

**Comment by alexicum** [comment]
And another note from Apollo docs:
http://dev.apollodata.com/react/receiving-updates.html#Subscriptions

The subscribeToMore subscription is stopped automatically when its dependent query is stopped, so we don’t need to unsubscribe manually. We do however need to unsubscribe manually if the props changed and we need to make a new subscription with different variables.

So unsubscribe is not needed in componentWillUnmount().

**Comment by bmsantos** [comment]
HI @alexicum,

The unsubscribe issue has been fixed for quite awhile now. See [here](https://github.com/bmsantos/apollo-graphql-subscriptions-example/blob/master/client-app/src/App.js#L50).

At the time there was very little to none documentation but I'm glad unsubscribe is not required in composnentWillUnmount. You can submit PRs if you wish.

Cheers

**Comment by alexicum** [comment]
Sorry, I mistook the template with this:
https://github.com/scaphold-io/slackr-graphql-subscriptions-starter-kit

**Comment by quadsurf** [comment]
@alexicum @helfer looks like auto-unsubscribe is not working, and that I do in fact need to unsubscribe in the "componentWillUnmount" lifecycle method, because i keep getting the following error:

Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
Please check the code for the Messages component.
* screens/Chat/Messages.js:126:26 in updateQuery

The setState that's being called, is inside my subscribeToMore updateQuery method, in a component that has been unmounted.

So how do I manually unsubscribe in "componentWillUnmount"? Calling this.props.data.subscribeToMore()  to unsubscribe, as suggested elsewhere, breaks my code with the following error: undefined is not an object (evaluating 'options.document'), and there doesn't exist an unsubscriber method on this.props.data , and neither does one exist in this.props.data.subscribeToMore({...})

Please note that this is Apollo v1... v2 is not an option for this app.

Please help, thank you!

**Comment by devmeyster** [comment]
@quadsurf Did you solve this issue? Running into the same bug while trying to test with Cavy
